use_frameworks!

install! 'cocoapods', :deterministic_uuids => false

platform :ios, '13.0'

target 'SociomileSupportSDK_Example' do
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'
  pod 'Alamofire'
  pod 'AlamofireImage', '~> 4.3'
  pod 'ImageSlideshow', '~> 1.9.0'
  
  pod 'FirebaseCore'
  pod 'FirebaseMessaging'

  pod 'SociomileSupportSDK/Debug', :path => '../'

  target 'SociomileSupportSDK_Tests' do
    inherit! :search_paths
  end
  
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = "13.0"
        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      end
    end
  end

end
