BUILD_DIR = /Users/aprikot/Projects/SCM-SDK/sociomile-ios-sdk/SociomileSupportSDK/Example
BUILD = @sh build.sh ${BUILD_DIR}
debug:
 @echo "Build Debug framework"
 ${BUILD} SociomileSupportSDK Debug
release:
 @echo "Build Release framework"
 ${BUILD} SociomileSupportSDK Release
